name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      # Biến môi trường MongoDB (lấy từ GitHub Secrets)
      SPRING_DATA_MONGODB_URI: ${{ secrets.SPRING_DATA_MONGODB_URI }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: server/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      JAR_NAME: server-0.0.1-SNAPSHOT.jar

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

          echo "Uploading JAR..."
          scp $JAR_NAME $EC2_USER@$EC2_HOST:/home/$EC2_USER/$JAR_NAME

          echo "Deploying on EC2..."
          ssh $EC2_USER@$EC2_HOST <<EOF
          set -e

          echo "Creating app directory if not exists..."
          sudo mkdir -p "/opt/my-spring-app"
          sudo chown $EC2_USER:$EC2_USER "/opt/my-spring-app"

          echo "Moving JAR to /opt/my-spring-app..."
          sudo mv "/home/$EC2_USER/$JAR_NAME" "/opt/my-spring-app/$JAR_NAME"
          sudo chown $EC2_USER:$EC2_USER "/opt/my-spring-app/$JAR_NAME"

          echo "Restarting app..."
          sudo systemctl stop my-spring-app.service || true
          sudo systemctl start my-spring-app.service
          sudo systemctl status my-spring-app.service
          EOF

